/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.maplecloudy.spider.schema;

import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import org.apache.avro.Schema;

@SuppressWarnings("all")
@org.apache.avro.specific.FixedSize(1)
public class BYTE extends org.apache.avro.specific.SpecificFixed {

  @Override
  public Schema getSchema() {
    // TODO Auto-generated method stub
    return null;
  }

  @Override
  public void readExternal(ObjectInput in) throws IOException {
    // TODO Auto-generated method stub
    
  }

  @Override
  public void writeExternal(ObjectOutput out) throws IOException {
    // TODO Auto-generated method stub
    
  }}
